import "./globals.css";
// import { ThemeProvider } from "@material-tailwind/react";
import Navbar from "@/components/topNavbar";


export const metadata = {
  title: "Secure PDF Genarator",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
          {/* <header> */}
            <Navbar />
          {/* </header> */}
          <main>
            {children}
          </main>
      </body>
    </html>
  );
}
